"use strict";
exports.__esModule = true;
exports.orders = [
    {
        "orderNumber": "FR10RJB6",
        "orderDate": "2019-10-21T12:07:43",
        "dropship": {
            "name": "Vision Source Lab -  Midland",
            "address": "Vision Source Lab -  Midland"
        },
        "status": "Pending",
        "statusDate": "2019-10-21T12:08:13",
        "billToAccountNumber": "4418",
        "shipToAccountNumber": "4418",
        "dropShipAccountNumber": "1699",
        "lineItems": [
            {
                "frame": {
                    "collectionContext": "None",
                    "isOrderable": false,
                    "showOrderLink": false,
                    "fpc": "410050000378",
                    "upc": "097963648660",
                    "categoryName": "COSTA Optical",
                    "moduleName": "18 - Must Have",
                    "brandName": "COSTA",
                    "roleType": "MODULE",
                    "wholesalePrice": "$48.45",
                    "purchasePrice": null,
                    "styleID": "7150307",
                    "styleName": "OCR101",
                    "collectionName": "COSTA",
                    "colorDescription": "146 MATTE DARK GRAY/MATTE",
                    "eyeSize": "57-15",
                    "temple": "140",
                    "exceptionType": null,
                    "statusCode": "L_ACTIVE",
                    "inStock": true,
                    "largeImageUrl": "http://content.visionweb.com/frameoe/19/large/410050000378.jpg",
                    "smallImageUrl": "http://content.visionweb.com/frameoe/19/small/410050000378.jpg"
                },
                "fpc": "410050000378",
                "orderType": "ForPatientToLab",
                "quantity": 1,
                "patientName": "FD4418 TEST",
                "rxId": "12345678",
                "price": null,
                "status": null,
                "date": null
            }
        ],
        "frameAccountId": "110783",
        "address": null,
        "fullName": null,
        "createdBy": null,
        "sqlOrderStatus": "Released to Warehouse",
        "sqlOrderStatusDate": "2019-10-21 17:37:00",
        "sqlRXOrderNumber": null,
        "sqlRXStatus": null,
        "sqlRXOrderTimeStamp": "0001-01-01 00:00:00",
        "rxOrderFoundInELINK": 0,
        "lineUseType": "Frame Only (Other Lab)",
        "rxOrderPlacedInLabID": null,
        "rxOrderPlacedInLabName": null,
        "slaFlag": false
    },
    {
        "orderNumber": "FR10RIG7",
        "orderDate": "2019-10-18T10:02:32",
        "dropship": {
            "name": "Office",
            "address": "Office"
        },
        "status": "Pending",
        "statusDate": "2019-10-18T14:23:28",
        "billToAccountNumber": "4418",
        "shipToAccountNumber": "4418",
        "dropShipAccountNumber": "4418",
        "lineItems": [
            {
                "frame": {
                    "collectionContext": "None",
                    "isOrderable": false,
                    "showOrderLink": false,
                    "fpc": "99010253136980",
                    "upc": "8056597038843",
                    "categoryName": "RayBan AF Optical",
                    "moduleName": "16 - Must Have All Fit",
                    "brandName": "RAY BAN",
                    "roleType": "MODULE",
                    "wholesalePrice": "$61.81",
                    "purchasePrice": null,
                    "styleID": "7151275",
                    "styleName": "0RX2185VF",
                    "collectionName": "RAY BAN",
                    "colorDescription": "Havana",
                    "eyeSize": "52-18",
                    "temple": "150",
                    "exceptionType": null,
                    "statusCode": "L_ACTIVE",
                    "inStock": true,
                    "largeImageUrl": "http://content.visionweb.com/frameoe/19/large/99010253136980.jpg",
                    "smallImageUrl": "http://content.visionweb.com/frameoe/19/small/99010253136980.jpg"
                },
                "fpc": "99010253136980",
                "orderType": "ForBoard",
                "quantity": 1,
                "patientName": "FOR BOARD",
                "rxId": "",
                "price": null,
                "status": null,
                "date": null
            }
        ],
        "frameAccountId": "110689",
        "address": null,
        "fullName": null,
        "createdBy": null,
        "sqlOrderStatus": "Released to Warehouse",
        "sqlOrderStatusDate": "2019-10-18 19:51:00",
        "sqlRXOrderNumber": null,
        "sqlRXStatus": null,
        "sqlRXOrderTimeStamp": "0001-01-01 00:00:00",
        "rxOrderFoundInELINK": 0,
        "lineUseType": "Frame Only (Board)",
        "rxOrderPlacedInLabID": null,
        "rxOrderPlacedInLabName": null,
        "slaFlag": false
    },
    {
        "orderNumber": "FR10RIFJ",
        "orderDate": "2019-10-18T08:06:26",
        "dropship": {
            "name": "Office",
            "address": "Office"
        },
        "status": "Pending",
        "statusDate": "2019-10-18T14:23:28",
        "billToAccountNumber": "4418",
        "shipToAccountNumber": "4418",
        "dropShipAccountNumber": "4418",
        "lineItems": [
            {
                "frame": {
                    "collectionContext": "None",
                    "isOrderable": false,
                    "showOrderLink": false,
                    "fpc": "99010253509210",
                    "upc": "8056597035170",
                    "categoryName": "RayBan Optical",
                    "moduleName": "08 - Iconic",
                    "brandName": "RAY BAN",
                    "roleType": "MODULE",
                    "wholesalePrice": "$70.24",
                    "purchasePrice": "$61.81",
                    "styleID": "7151475",
                    "styleName": "0RX2185V",
                    "collectionName": "RAY BAN",
                    "colorDescription": "Havana",
                    "eyeSize": "52-18",
                    "temple": "145",
                    "exceptionType": null,
                    "statusCode": "L_ACTIVE",
                    "inStock": true,
                    "largeImageUrl": "http://content.visionweb.com/frameoe/19/large/99010253509210.jpg",
                    "smallImageUrl": "http://content.visionweb.com/frameoe/19/small/99010253509210.jpg"
                },
                "fpc": "99010253509210",
                "orderType": "ForBoard",
                "quantity": 1,
                "patientName": "FOR BOARD",
                "rxId": "",
                "price": null,
                "status": null,
                "date": null
            }
        ],
        "frameAccountId": "110689",
        "address": null,
        "fullName": null,
        "createdBy": null,
        "sqlOrderStatus": "Released to Warehouse",
        "sqlOrderStatusDate": "2019-10-18 19:51:00",
        "sqlRXOrderNumber": null,
        "sqlRXStatus": null,
        "sqlRXOrderTimeStamp": "0001-01-01 00:00:00",
        "rxOrderFoundInELINK": 0,
        "lineUseType": "Frame Only (Board)",
        "rxOrderPlacedInLabID": null,
        "rxOrderPlacedInLabName": null,
        "slaFlag": false
    },
    {
        "orderNumber": "FR10RIEE",
        "orderDate": "2019-10-17T16:13:59",
        "dropship": {
            "name": "Office",
            "address": "Office"
        },
        "status": "Pending",
        "statusDate": "2019-10-18T14:23:27",
        "billToAccountNumber": "4418",
        "shipToAccountNumber": "4418",
        "dropShipAccountNumber": "4418",
        "lineItems": [
            {
                "frame": {
                    "collectionContext": "None",
                    "isOrderable": false,
                    "showOrderLink": false,
                    "fpc": "410878000239",
                    "upc": "810434025117",
                    "categoryName": "Bloom Optical",
                    "moduleName": "16 - Must Have",
                    "brandName": "BLOOM",
                    "roleType": "MODULE",
                    "wholesalePrice": "$0.00",
                    "purchasePrice": "$0.00",
                    "styleID": "7151906",
                    "styleName": "BL Carla",
                    "collectionName": "BLOOM",
                    "colorDescription": "BLU BLUE",
                    "eyeSize": "50-16",
                    "temple": "135",
                    "exceptionType": null,
                    "statusCode": "L_ACTIVE",
                    "inStock": true,
                    "largeImageUrl": "http://content.visionweb.com/frameoe/19/large/410878000239.jpg",
                    "smallImageUrl": "http://content.visionweb.com/frameoe/19/small/410878000239.jpg"
                },
                "fpc": "410878000239",
                "orderType": "ForBoard",
                "quantity": 1,
                "patientName": "FOR BOARD",
                "rxId": "",
                "price": null,
                "status": null,
                "date": null
            }
        ],
        "frameAccountId": "110689",
        "address": null,
        "fullName": null,
        "createdBy": null,
        "sqlOrderStatus": "Released to Warehouse",
        "sqlOrderStatusDate": "2019-10-18 19:51:00",
        "sqlRXOrderNumber": null,
        "sqlRXStatus": null,
        "sqlRXOrderTimeStamp": "0001-01-01 00:00:00",
        "rxOrderFoundInELINK": 0,
        "lineUseType": "Frame Only (Board)",
        "rxOrderPlacedInLabID": null,
        "rxOrderPlacedInLabName": null,
        "slaFlag": false
    },
    {
        "orderNumber": "FR10Q8OV",
        "orderDate": "2019-10-08T09:07:14",
        "dropship": {
            "name": "Vision Source Lab -  Midland",
            "address": "Vision Source Lab -  Midland"
        },
        "status": "Pending",
        "statusDate": "2019-10-08T18:14:41",
        "billToAccountNumber": "4418",
        "shipToAccountNumber": "4418",
        "dropShipAccountNumber": "1699",
        "lineItems": [
            {
                "frame": {
                    "collectionContext": "None",
                    "isOrderable": false,
                    "showOrderLink": false,
                    "fpc": "410878000208",
                    "upc": "810434024981",
                    "categoryName": "Bloom Optical",
                    "moduleName": "16 - Must Have",
                    "brandName": "BLOOM",
                    "roleType": "MODULE",
                    "wholesalePrice": "$50.36",
                    "purchasePrice": null,
                    "styleID": "7151915",
                    "styleName": "BL JADA",
                    "collectionName": "BLOOM",
                    "colorDescription": "PLUM PLUM",
                    "eyeSize": "49-17",
                    "temple": "135",
                    "exceptionType": null,
                    "statusCode": "L_ACTIVE",
                    "inStock": true,
                    "largeImageUrl": "http://content.visionweb.com/frameoe/19/large/410878000208.jpg",
                    "smallImageUrl": "http://content.visionweb.com/frameoe/19/small/410878000208.jpg"
                },
                "fpc": "410878000208",
                "orderType": "ForPatientToLab",
                "quantity": 1,
                "patientName": "test test",
                "rxId": "SP1UF1WF",
                "price": null,
                "status": null,
                "date": null
            }
        ],
        "frameAccountId": "110783",
        "address": null,
        "fullName": null,
        "createdBy": null,
        "sqlOrderStatus": "Released to Warehouse",
        "sqlOrderStatusDate": "2019-10-08 23:07:00",
        "sqlRXOrderNumber": null,
        "sqlRXStatus": null,
        "sqlRXOrderTimeStamp": "0001-01-01 00:00:00",
        "rxOrderFoundInELINK": 0,
        "lineUseType": "Frame Only (Other Lab)",
        "rxOrderPlacedInLabID": null,
        "rxOrderPlacedInLabName": null,
        "slaFlag": false
    }
];
